spring.application.name=CineSphere


spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/cinesphere
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=key
razorpay.key.secret=sec_key

spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cinesphere.tickets@gmail.com
spring.mail.password=app pass
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

