spring.application.name=CineSphere


spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/cinesphere
spring.datasource.password=krishna04

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_SYc2WglxFRFwqY
razorpay.key.secret=WR7Oy1HxnUX9DcWn3dVbhnsK



