package com.cinesphere.main.service.impl;

import java.math.BigDecimal;

import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.cinesphere.main.entity.Booking;
import com.cinesphere.main.entity.Payment;
import com.razorpay.RazorpayClient;
import com.razorpay.RazorpayException;
import com.razorpay.Refund;

import jakarta.transaction.Transactional;

@Service
public class RefundService {

	@Autowired
	private RazorpayClient razorpayClient; // Injected from your Config

	@Transactional
	public String initiateRefund(Booking booking, Payment payment) {
		try {
			// 1. Prepare Refund Request
			JSONObject refundRequest = new JSONObject();

			// Razorpay expects amount in PAISE (e.g., ₹100 = 10000)
			BigDecimal amountInPaise = payment.getAmount().multiply(new BigDecimal(100));
			refundRequest.put("amount", amountInPaise.intValue());
			refundRequest.put("speed", "normal"); // or "optimum"

			// 2. Call Razorpay API using the original Payment ID
			Refund razorpayRefund = razorpayClient.payments.refund(payment.getPaymentId(), refundRequest);

			// 3. Return the Refund ID generated by Razorpay
			return razorpayRefund.get("id");

		} catch (RazorpayException e) {
			throw new RuntimeException("Razorpay Refund Failed: " + e.getMessage());
		}
	}
}